---
tap_install:
  values:
    profile: run
    excluded_packages: # installed by TMC elsewhere
    - fluxcd.source.controller.tanzu.vmware.com
    - namespace-provisioner.apps.tanzu.vmware.com
    - tap-telemetry.tanzu.vmware.com 
    - contour.tanzu.vmware.com
    ceip_policy_disclosed: true # Installation fails if this is set to 'false'

    cnrs:
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
      ingress:
        internal:
          namespace: tanzu-system-ingress
        external:
          namespace: tanzu-system-ingress


    tap_gui:
      app_config:
          kubernetes:
              serviceLocatorMethods:
                  type: 'multiTenant'
              clusterLocatorMethods:
                  - type: 'config'
                    clusters:
                    - url: https://192.168.1.119:6443
                      name: tap-run-1
                      authProvider: serviceAccount
                      serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6IlVhRkJyRzFCOGtXaUNKeUVReFdGYU4xNVFYZkE3VFU3OFdsOUNwc2l5dDgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0YXAtZ3VpIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMGUyZTA2MmItZjFhZS00YjllLTgwOWItYTQyODg1ZjYyZWEwIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnRhcC1ndWk6dGFwLWd1aS12aWV3ZXIifQ.nrAS7onKSi6GUdag5pXB5-AgQMTGCnDo7OBQBFs94c-8zDqvYjNWvLVqAgI-Iv4BGFwfIQg6RrHeRB14ZDUQ9dKgCli-WCAOg9Bn28Sbe7CbbAFaRd0Qpu7mltUR1HvjY1EOZywZUKVJuNNdl22mo-QBnu8Ut2QQb9xjb5IVguHC3vCM7NKIoV9g4e0HkZNejICyfqBgLgXcCS90tIZaTv0Y7WhxWPKgJlXhRc_3ZYe0hvKIR8HCRIvL8CGqHAYHs-DDuNSItEBZx88o-VW0LrLdGYZtZNuzJ_oRhwxHtrrUOcSfIBZkZFXMiqTEU5D32zMZecDpR8xuF_fvLqyEdA
                      skipTLSVerify: true
                      skipMetricsLookup: true
          auth:
              allowGuestAccess: true
    buildservice:
      kp_default_repository: "registry.gcp.ellin.net/tap/build"

    supply_chain: basic

    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: clusters/common/namespace-provisioner
        url: https://github.com/jeffellin/single
      additional_sources:
      - git:
          ref: origin/main
          subPath: clusters/common/namespaces/dev
          url: https://github.com/jeffellin/single.git
        path: _ytt_lib/dev-namespace-setup
      import_data_values_secrets:
      - name: workload-git-auth
        namespace: tap-install
        create_export: true
      overlay_secrets:
      - name: workload-git-auth-overlay
        namespace: tap-install
        create_export: true
    
