---
tap_install:
  values:
    profile: run
    excluded_packages: # installed by TMC elsewhere
    - fluxcd.source.controller.tanzu.vmware.com
    - contour.tanzu.vmware.com
    - namespace-provisioner.apps.tanzu.vmware.com
    - tap-telemetry.tanzu.vmware.com 
    
    ceip_policy_disclosed: true # Installation fails if this is set to 'false'

    cnrs:
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
      ingress:
        internal:
          namespace: tanzu-system-ingress
        external:
          namespace: tanzu-system-ingress


    tap_gui:
      app_config:
          auth:
              allowGuestAccess: true
    buildservice:
      kp_default_repository: "registry.gcp.ellin.net/tap/build"

    supply_chain: basic

    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: clusters/common/namespace-provisioner
        url: https://github.com/jeffellin/single
      additional_sources:
      - git:
          ref: origin/main
          subPath: clusters/common/namespaces/dev
          url: https://github.com/jeffellin/single.git
        path: _ytt_lib/dev-namespace-setup
      import_data_values_secrets:
      - name: workload-git-auth
        namespace: tap-install
        create_export: true
      overlay_secrets:
      - name: workload-git-auth-overlay
        namespace: tap-install
        create_export: true
    
