---
tap_install:
  values:
    profile: run
    excluded_packages: # installed by TMC elsewhere
    - fluxcd.source.controller.tanzu.vmware.com
    - tap-telemetry.tanzu.vmware.com 
    - contour.tanzu.vmware.com
    ceip_policy_disclosed: true # Installation fails if this is set to 'false'
    shared:
      ingress_issuer: letsencrypt-contour-cluster-issuer

    appliveview_connector:
      activateAppLiveViewSecureAccessControl: false
      backend:
        host: appliveview.view.lab.ellin.net
        caCertData: |-
          -----BEGIN CERTIFICATE-----
          MIIFCTCCA/GgAwIBAgISBIrvneMn6/mudlcl1wJeT/IdMA0GCSqGSIb3DQEBCwUA
          MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
          EwJSMzAeFw0yMzEyMDQxOTI3NDZaFw0yNDAzMDMxOTI3NDVaMCkxJzAlBgNVBAMT
          HmFwcGxpdmV2aWV3LnZpZXcubGFiLmVsbGluLm5ldDCCASIwDQYJKoZIhvcNAQEB
          BQADggEPADCCAQoCggEBAOWqqUWmI4npdVV4FnKS+pb6b3RvdW+bmM1aJbZBHVsd
          S6QpshyDdIMbwPj/td+VKNirutzBue3uOItX/ZBtXDujhW70oI+JGwROnTcCL4Tj
          TZJGKlfVLXthl2ktm6cvQl53znTQ/s2cFEyYuC1BkGtTK0JMbMtrkiJBtiKoeBww
          lhPfmyyyv/jpgVKAH0tMxIgnuhHt30JEics4WlD+/q8/1WThkffX+Dx8I6ZAhYiy
          P2fHbo5Zuo/YwyGwenR3iRTgCjWgTeSH5l17aLUjX2lH3aUcA6rkDAz9UaLTrhS3
          x/COhzKu2m/E1tWbnJTRYK56dpthZ1PWIhN+AAS1rK8CAwEAAaOCAiAwggIcMA4G
          A1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYD
          VR0TAQH/BAIwADAdBgNVHQ4EFgQUlOfv4fkD47h6tFhrCAiqhhrnIzowHwYDVR0j
          BBgwFoAUFC6zF7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsG
          AQUFBzABhhVodHRwOi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6
          Ly9yMy5pLmxlbmNyLm9yZy8wKQYDVR0RBCIwIIIeYXBwbGl2ZXZpZXcudmlldy5s
          YWIuZWxsaW4ubmV0MBMGA1UdIAQMMAowCAYGZ4EMAQIBMIIBBAYKKwYBBAHWeQIE
          AgSB9QSB8gDwAHYASLDja9qmRzQP5WoC+p0w6xxSActW3SyB2bu/qznYhHMAAAGM
          NoP06wAABAMARzBFAiEAvmo9/SQwFtCm7BjhK5VdRbHIFZcNSR2YUq61rDK54kgC
          IC00cnwNQhHhLA9EFy76tW1pVxN3COAMrYJwnnar7P5nAHYA7s3QZNXbGs7FXLed
          tM0TojKHRny87N7DUUhZRnEftZsAAAGMNoP1kAAABAMARzBFAiAc7PLcRN8A0Vz6
          DOL4qhfdktTwWme9AgS5V1qyW7JNNgIhAO2XndVJvXcVbiKkXwlGCEkgng0mnoJh
          XJCpkOZGopUfMA0GCSqGSIb3DQEBCwUAA4IBAQAGWRZtD394onaD28Iq7kCeySl9
          NN1Yylcha+U/f66V11Wc0j1A18iMVP7PDSK7zjcEC3odHHDIIiB0VBemqFH762Re
          XSsv1wtLCbZkFJD7kKXc73PflinQtziKOz9EjckK1nXffcgsFj1IxUfySrdfKosB
          WQ0TDwZ9cimErI6pxkMQdYJqVU1vH8I8gDq6xYoa+HlsNofXRho5KhPCuDz8GSha
          kFKOGyB5VNWDORNfdIJ4O3JcsgKcIWNrXvv5NWkB5vdq7i+NYkHw6JtBNjJ79Ubz
          go148j+v4/bKFVcZyGaTL5zy5nCHEo9Gm6qnaCGMP9leaWcfv2XP73Olvd7l
          -----END CERTIFICATE-----
          -----BEGIN CERTIFICATE-----
          MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
          TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
          cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
          WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
          RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
          AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
          R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
          sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
          NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
          Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
          /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
          AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
          Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
          FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
          AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
          Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
          gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
          PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
          ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
          CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
          lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
          avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
          yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
          yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
          hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
          HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
          MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
          nLRbwHOoq7hHwg==
          -----END CERTIFICATE-----
          -----BEGIN CERTIFICATE-----
          MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
          MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
          DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
          TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
          cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
          AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
          ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
          wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
          LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
          4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
          bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
          sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
          Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
          FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
          SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
          PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
          TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
          SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
          c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
          +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
          ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
          b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
          U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
          MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
          5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
          9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
          WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
          he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
          Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
          -----END CERTIFICATE-----

          
          
                  sslDeactivated: False
        ingressEnabled: True
        
    api_auto_registration:
      tap_gui_url: "https://tap-gui.view.lab.ellin.net"

    cnrs:
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
      ingress:
        internal:
          namespace: tanzu-system-ingress
        external:
          namespace: tanzu-system-ingress


    tap_gui:
      app_config:
          auth:
              allowGuestAccess: true
    buildservice:
      kp_default_repository: "registry.gcp.ellin.net/tap/build"

    supply_chain: basic
    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: clusters/common/namespace-provisioner
        url: https://github.com/jeffellin/single
      additional_sources:
      - git:
          ref: origin/main
          subPath: clusters/common/namespaces/qa
          url: https://github.com/jeffellin/single.git
        path: _ytt_lib/qa-namespace-setup
      import_data_values_secrets:
      - name: workload-git-auth
        namespace: tap-install
        create_export: true
      overlay_secrets:
      - name: workload-git-auth-overlay
        namespace: tap-install
        create_export: true
