tap_install:
    sensitive_values:
        shared:
            image_registry:
                project_path: ENC[AES256_GCM,data:w7izIczkkzx0Fza8Cll2qxzuCcl7DnAJ4j0=,iv:pwAuIMBb0hc7QCuoByM+Uw44+2IMnd1mz8FyqmnxJa8=,tag:52zMZ9v2OxRAaRshxXnFlA==,type:str]
                username: ENC[AES256_GCM,data:p8noss0=,iv:KZTleaMJmYzIvjTYt8Q54GQFzYt60uKp7st82apOftw=,tag:b3E9RsviEUyRrv2MfCd4jw==,type:str]
                password: ENC[AES256_GCM,data:kHIED5x5ESYdBad3BZZ1s2Tk,iv:7Th1Mh3zEciaT5CUhtbPMIG284clNxwjrDG2UflqjsM=,tag:jTDrUFk9rKHVU/cAKoHedg==,type:str]
        tap_gui:
            app_config:
                techdocs: null
                builder: ENC[AES256_GCM,data:2HuC/c9rbrU=,iv:cbmIHoTklO16N/WbYxk9gOCnw0zlJT38usc8Urb0dE4=,tag:1XneMM1jxfm3oz1GRuERFQ==,type:str]
                publisher:
                    type: ENC[AES256_GCM,data:GeJtr74=,iv:e34fXS8XPUCG2mPEg8kHyOWSW9EwH9qWlfcKjWRj8hY=,tag:sc0OWKPRx4Tivf10IsDITA==,type:str]
                    awsS3:
                        bucketName: ENC[AES256_GCM,data:ydv4NPiN/2xn4lGfnV/oMw==,iv:24kaAMpP3HccHob1AjfK8YkYwYgXkSJxXUXOw1odbZI=,tag:yKNel3aehtYz5Ihbu/cYzA==,type:str]
                        credentials:
                            accessKeyId: ENC[AES256_GCM,data:4vBA77lBRW+jd8KHjKQvFeqzufA=,iv:RBPiWwduf93S1uX23+66Da1GEN1As88YHQN9xzzh4ro=,tag:ZOs9pXoVmbjt7SNyQ9fvKQ==,type:str]
                            secretAccessKey: ENC[AES256_GCM,data:VUUybEbs7JqAwWOBcStECR+M5l1VBFACLQlqWJ/9zFudgVu9ThRfYg==,iv:pyKkB/Cw/Uht+XxMbUK6pu+v/SoDRif9YbP5beTrwk4=,tag:pr0BYP8oNS/mlEwNgptmhQ==,type:str]
                        region: ENC[AES256_GCM,data:5Z35kNDbWeaA,iv:m/YHWRZF7KW0/xjxDMya1QxyRaIt1LHLonNqftluBjg=,tag:U1o+5AtyZrTv9VAH8lf9Xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sul2yf3vwkkzqzq58v6cpsn9e6sn2sl09p5qqgqfr9fq70tez9nqukh9sa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT1NpRU1iaytlcEJ5cldF
            dlJrOWRWOVRTYW9yTmg5U0d0dEFJek53NUdNCnpLMWl4dWoxc3VJbW1wcHF1RGxW
            RElUUjFQbjd6MHJzRFpoQTVXUGlySFkKLS0tIHNCeDlycEZZb2wwcmRYRDZ2M2Iy
            U09zc1VYaDlBck9kSEtOazVTbjJ2YmcKx7JUNbzDUsElvD3bBlr59CT63XqnKaKA
            GLAHFBN9fI4xEpAoMSSLPBIKtm9y2FPxbs4u38c4iHh+Wynmzx+tbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-20T19:11:41Z"
    mac: ENC[AES256_GCM,data:4RHpivsbG/N220TGHzqw9zeT9u42faRuCOI2WxRqvLXq6hJQGQqG7VAQlKDLLxwNTyb5MUyA2B/h61wP51T2uPFk7ZxfzEK3vVtuRnADv1ediwqFWJIR+aqurMZVJvBibt7Ys1t7EWwnMfgN10I24JmUoBxPgCXmA0Kh5ghGns4=,iv:VWIivSVM1g2/4Cxi4qtaMDQvcKdl8z2UhY1CBYxKMfs=,tag:chPqu+aRZzDM5IJ4rhPZ3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
