---
tap_install:
  values:
    profile: full
    
    ceip_policy_disclosed: true # Installation fails if this is set to 'false'

    cnrs:
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
      domain_name: "foo.amer.end2end.link"
      ingress:
        internal:
          namespace: tanzu-system-ingress
        external:
          namespace: tanzu-system-ingress
    shared:
      ingress_domain: foo.amer.end2end.link
      image_registry:
        project_path: registry.gcp.ellin.net/tap/tbs

    buildservice:
      kp_default_repository: "registry.gcp.ellin.net/tap/build"

    supply_chain: basic
