---
tap_install:
  values:
    profile: full
    excluded_packages: # installed by TMC elsewhere
    - tap-telemetry.tanzu.vmware.com 
    
    ceip_policy_disclosed: true # Installation fails if this is set to 'false'

    cnrs:
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
      domain_name: home.lab.ellin.net
      ingress:
        internal:
          namespace: tanzu-system-ingress
        external:
          namespace: tanzu-system-ingress


    tap_gui:
      app_config:
          auth:
              allowGuestAccess: true
    shared:
      ingress_domain: home.lab.ellin.net
      activateAppLiveViewSecureAccessControl: false
      kubernetes_version: "1.25.9"
      image_registry:
        project_path: "registry.gcp.ellin.net/tap3"    
    supply_chain: basic
      ootb_supply_chain_basic:
        gitops:
          commit_strategy: pull_request
          branch: test
          repository_owner: tanzu-end-to-end
          server_address: https://github.com
          ssh_secret: git-https
          pull_request:
            commit_branch: supply-chain
            server_kind: github
            pull_request_title: Ready for review
            pull_request_body: Pull Request by TAP
    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: clusters/common/namespace-provisioner
        url: https://github.com/jeffellin/single
      additional_sources:
      - git:
          ref: origin/main
          subPath: clusters/common/namespaces/dev
          url: https://github.com/jeffellin/single.git
        path: _ytt_lib/dev-namespace-setup
      import_data_values_secrets:
      - name: workload-git-auth
        namespace: tap-install
        create_export: true
      overlay_secrets:
      - name: workload-git-auth-overlay
        namespace: tap-install
        create_export: true
    
