apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-https
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap"
    tekton.dev/git-0: https://github.com
spec:
  fromNamespace: tap-install