---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: crossplane-provider-app
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-group: crossplane/provider
    kapp.k14s.io/change-rule: "upsert after upserting tap"
spec:
  serviceAccountName: sync-sa
  syncPeriod: 1m
  fetch:
  - git: 
      url: https://github.com/jeffellin/single.git
      ref: main
  template:
  - ytt:
      paths:
      - clusters/common/app-contents/crossplane
  deploy:
  - kapp: {}