apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider
  annotations:
    kapp.k14s.io/change-group: crossplane/config
    kapp.k14s.io/change-rule: "upsert after upserting crossplane/provider"
spec:
  credentials:
    source: InjectedIdentity