apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
  annotations:
    kapp.k14s.io/change-group: crossplane-provider
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-aws:v0.40.0
  skipDependencyResolution: true
  controllerConfigRef:
    name: aws-config